# Default Skiko CI
name: CI

on:
  push:
    branches: [ master ]
  # TODO: temporary for faster tests, restore!
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  macos:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        name: 'Check out code'

      - uses: actions/setup-java@v3
        name: 'Set up JDK 11'
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

      - shell: bash
        name: 'Publish to Maven Local, check AWT sample'
        run: |
          ./gradlew --stacktrace --info -Pskiko.native.enabled=true :skiko:publishToMavenLocal :skiko:publishToBuildRepo -Pskiko.native.enabled=true -Pskiko.wasm.enabled=true -Pskiko.android.enabled=true

      - uses: actions/upload-artifact@v4
        name: 'Save test results as artifact'
        if: always()
        with:
          name: test-reports-macos
          path: ./skiko/build/repo
          retention-days: 5

  iOS:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
        name: 'Check out code'

      - uses: actions/setup-java@v3
        name: 'Set up JDK 11'
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

      - name: 'Print the devices list'
        run: xcrun simctl list devices available --json

      # install jq - cli tool for json querying
      # retrieve the device .udid to use in tests and store it in env var
      - name: 'Set Up Simulator UUID'
        run: |
          brew install jq &&
          IOS_SIM_UUID=$(xcrun simctl list devices available --json | jq -r '.devices."com.apple.CoreSimulator.SimRuntime.iOS-17-0"[] | select(.name == "iPhone 14") | .udid') &&
          echo "IOS_SIM_UUID=$IOS_SIM_UUID" >> $GITHUB_ENV

      - name: 'Print Selected UUID'
        run: echo $IOS_SIM_UUID

      # TODO run iOS specific tests on iPhone simulator
      - shell: bash
        name: 'Publish to Maven Local'
        run: ./gradlew --stacktrace --info -Pskiko.native.enabled=true :skiko:publishToMavenLocal :skiko:publishToBuildRepo -Pskiko.native.enabled=true -Pskiko.wasm.enabled=true -Pskiko.android.enabled=true

      - uses: actions/upload-artifact@v4
        name: 'Save test results as artifact'
        if: always()
        with:
          name: test-reports-ios
          path: ./skiko/build/repo
          retention-days: 5

  linux:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        name: 'Check out code'

      - uses: actions/setup-java@v3
        name: 'Set up JDK 11'
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

      - uses: nttld/setup-ndk@v1
        name: 'Set up Android NDK'
        id: setup-ndk
        with:
          ndk-version: r21e

      - uses: android-actions/setup-android@v2
        name: 'Set up Android SDK'

      - shell: bash
        name: 'Set up Linux build environment'
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          # TODO: simplify installation of compilers.
          sudo apt-get update -y
          sudo apt-get install build-essential software-properties-common -y
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update -y
          sudo apt-get install build-essential software-properties-common -y
          sudo apt-get update
          sudo apt-get install gcc-9 g++-9 -y
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
          sudo update-alternatives --config gcc
          sudo apt-get install ninja-build fontconfig libfontconfig1-dev libglu1-mesa-dev libxrandr-dev libdbus-1-dev zip xvfb -y
          sudo apt-get install gcc-9-aarch64-linux-gnu g++-9-aarch64-linux-gnu multistrap -y
          sudo update-alternatives --install /usr/bin/aarch64-linux-gnu-gcc aarch64-linux-gnu-gcc /usr/bin/aarch64-linux-gnu-gcc-9 60 --slave /usr/bin/aarch64-linux-gnu-g++ aarch64-linux-gnu-g++ /usr/bin/aarch64-linux-gnu-g++-9
          sudo update-alternatives --config aarch64-linux-gnu-gcc
          sudo Xvfb :0 -screen 0 1280x720x24 &

      - shell: bash
        name: 'Publish to Maven Local, check AWT sample'
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          ./gradlew --no-daemon --stacktrace --info -Pkotlin.native.cacheKind.linuxX64=none :skiko:publishToMavenLocal :skiko:publishToBuildRepo -Pskiko.native.enabled=true -Pskiko.wasm.enabled=true -Pskiko.android.enabled=true
          ./gradlew --no-daemon -Pskiko.android.enabled=true :skiko:publishSkikoJvmRuntimeAndroidX64PublicationToMavenLocal :skiko:publishSkikoJvmRuntimeAndroidArm64PublicationToMavenLocal :skiko:publishAndroidPublicationToMavenLocal

      - uses: actions/upload-artifact@v4
        name: 'Save test results as artifact'
        if: always()
        with:
          name: test-reports-linux
          path: ./skiko/build/repo
          retention-days: 5

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        name: 'Check out code'

      - uses: microsoft/setup-msbuild@v1

      - uses: ilammy/msvc-dev-cmd@v1

      - uses: actions/setup-java@v3
        name: 'Set up JDK 11'
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'gradle'

      - shell: bash
        name: 'Publish to Maven Local, check AWT sample'
        run: |
          ./gradlew --stacktrace --info :skiko:publishToMavenLocal :skiko:publishToBuildRepo -Pskiko.native.enabled=true -Pskiko.wasm.enabled=true -Pskiko.android.enabled=true

      - uses: actions/upload-artifact@v4
        name: 'Save test results as artifact'
        if: always()
        with:
          name: test-reports-windows
          path: ./skiko/build/repo
          retention-days: 5

