name: Skiko Tests
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  linux-arm:
    name: 'Linux (arm64)'
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v3
        name: 'Check out code'

      - shell: bash
        run: |
          sudo apt update
          sudo apt install binutils build-essential software-properties-common -y
          sudo apt install zip unzip git curl wget xvfb -y
          sudo apt install fontconfig libfontconfig1-dev libglu1-mesa-dev libegl1-mesa-dev libxrandr-dev libdbus-1-dev -y
          sudo apt install openjdk-21-jdk -y
          export LIBGL_ALWAYS_SOFTWARE=1
          echo "export LIBGL_ALWAYS_SOFTWARE=1" >> $GITHUB_ENV

      - shell: bash
        name: 'Start X Server'
        run: |
          Xvfb :1 -screen 0 1920x1080x24 -extension RANDR +extension GLX &
          echo "DISPLAY=:1.0" >> $GITHUB_ENV

      - shell: bash
        name: 'Run Linux (arm64) Tests'
        working-directory: skiko
        run: |
          chmod +x ./test.kexe
          ./test.kexe

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports-linux-arm
          path: |
            ./skiko/build/reports/tests
            ./skiko/src/jvmTest/screenshots/*_actual.png
          retention-days: 5

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "./skiko/build/test-results/**/TEST-*.xml"
        if: always()
